### PR TITLE
Issue #966: Throw an exception if environment variable is not set

### LINKED ISSUE #966: Throw an exception if environment variable is not set

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**
Closes #966.

### CODE REVIEW

File: src/RestApi/RestApiFactory.php [hunk 1]
```diff
@@ -83,13 +83,12 @@ private function getCatalogImportDirectoryConfig() : string
...
-        $catalogImportDirectory = $configReader->get('catalog_import_directory');
 
-        if (null === $catalogImportDirectory) {
-            return __DIR__ . '/../../tests/shared-fixture';
+        if ($configReader->has('catalog_import_directory')) {
+            return $configReader->get('catalog_import_directory');
         }
 
-        return $catalogImportDirectory;
+        return __DIR__ . '/../../tests/shared-fixture';
```
Comment (Vinai) [inline src/RestApi/RestApiFactory.php]: Ugh. Maybe this can be cleaned up in this PR, too?

**Comment by tim-bezhashvyly** [comment]
All done. Ready for next review.
