### PR TITLE
Issue #1014: Fix multi-word search for product search page

### LINKED ISSUE #1014: Split product search REST API term by words

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**
Closes #1014.

### CODE REVIEW

File: tests/Unit/Suites/ProductSearch/ContentDelivery/DefaultFullTextCriteriaBuilderTest.php [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+        $this->assertEquals($expectedCriteria, $builder->createFromString('foo bar'));
+    }
+
+    public function fullTextSearchTermCombinationOperatorProvider(): array
+    {
+        return [
+            [CompositeSearchCriterion::OR_CONDITION],
+            [CompositeSearchCriterion::AND_CONDITION],
+        ];
+    }
```
Comment (Vinai) [inline tests/Unit/Suites/ProductSearch/ContentDelivery/DefaultFullTextCriteriaBuilderTest.php]: Can you add tests for `createFromString()` with `''` and `' '` please?

Comment (tim-bezhashvyly) [inline tests/Unit/Suites/ProductSearch/ContentDelivery/DefaultFullTextCriteriaBuilderTest.php]: Very good point. Handled.

**Comment by tim-bezhashvyly** [comment]
Ready for next review.
