### PR TITLE
Issue: #964: Don't throw an exception in case REST API call has no "Accept" header

### LINKED ISSUE #964: Don't throw an exception in case REST API call has no "Accept" header
Currently if REST API is called without "Accept" header an exception is thrown. This does not allow to forward request to further backend(s).

Instead of throwing an exception API router must just reject the request passing it further down the chain.

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**
Closes #964.

### CODE REVIEW

File: tests/Unit/Suites/RestApi/ApiRouterTest.php [hunk 1]
```diff
@@ -45,15 +46,27 @@ public function testNullIsReturnedIfUrlIsNotLedByApiPrefix()
...
         $this->stubHttpRequest->method('getPathWithoutWebsitePrefix')->willReturn('api/foo');
         $result = $this->apiRouter->route($this->stubHttpRequest);
 
         $this->assertNull($result);
     }
 
+    public function testReturnsNullIfRequestHasNoAcceptHeader()
+    {
+        $this->stubHttpRequest->method('hasHeader')->with('Accept')->willReturn(false);
+        $this->stubHttpRequest->method('getHeader')->with('Accept')->willThrowException(new HeaderNotPresentException);
```
Comment (Schrank) [inline tests/Unit/Suites/RestApi/ApiRouterTest.php]: This method is never called, right? Maybe better:

    $this->stubHttpRequest->expects($this->never())->method('getHeader');

Comment (tim-bezhashvyly) [inline tests/Unit/Suites/RestApi/ApiRouterTest.php]: I don't see much difference but to me it looks like `$this->never()` is more of sticking to implementation while `willThrowException(..)` is just mimicking stubbed class logic.

File: src/RestApi/ApiRouter.php [hunk 2]
```diff
@@ -34,10 +34,9 @@ public function route(HttpRequest $request)
...
 
-        $acceptHeader = $request->getHeader('Accept');
-        if (!preg_match(
+        if (! $request->hasHeader('Accept') || ! preg_match(
             '/^application\/vnd\.lizards-and-pumpkins\.\w+\.v(\d+)\+(?:json|xml)$/',
-            $acceptHeader,
+            $request->getHeader('Accept'),
             $matchedVersion
         )) {
             return null;
```
Comment (Vinai) [inline src/RestApi/ApiRouter.php]: Please extract this into a method `getRequestedApiVersion()`.
Please also use named capture groups in the regex so `$matchedVersion['version']` can be used instead of `$matchedVersion[1]`.

Comment (tim-bezhashvyly) [inline src/RestApi/ApiRouter.php]: As `preg_match` is doing 2 things here (putting matches into an array and returning boolean if a match has been found) extracting it into a method is problematic.

I have added a named capture in #967 PR.
