### PR TITLE
Issue #1085: Add product lisiting meta data to product listing page

### LINKED ISSUE #1085: meta info is missing in page body on integration tests
Especially:

    \LizardsAndPumpkins\ProductListingTest::testProductListingWithEmptyUrlKeyReturnsHomepage
    \LizardsAndPumpkins\ProductListingTest::testProductListingPageHtmlIsReturned

Therefore we can't find the title/description on the body and `\LizardsAndPumpkins\ProductListingTest::testProductListingWithEmptyUrlKeyReturnsHomepage` fails on https://github.com/lizards-and-pumpkins/catalog/pull/1083

Body from `\LizardsAndPumpkins\ProductListingTest::testProductListingPageHtmlIsReturned`

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv=“Content-Type” content=“text/html; charset=utf-8" />
<title></title>
<link type=“text/css” rel=“stylesheet” href=“http://example.com/css/product_listing.css” />
<script data-main=“http://example.com/js/product_listing” src=“http://example.com/js/lib/require.js”></script>

</head>
<body>
    <script>var filterNavigationJson = {“gender”:[{“value”:“Herren”,“count”:1}],“brand”:[{“value”:“Adidas”,“count”:1}],“price”:[{“value”:“149200",“count”:1}],“color”:[{“value”:“d90000",“count”:1}]}</script>

    <script>
    var productListingJson = [{“product_id”:“288193NEU”,“tax_class”:“19%“,”type_code”:“simple”,“attributes”:{“url_key”:“adilette”,“name”:“Adilette”,“category”:“sale”,“brand”:“Adidas”,“gender”:“Herren”,“stock_qty”:“1",“backorders”:“false”,“color”:“d90000",“series”:“Adilette”,“news_from_date”:“2015-02-25 00:00:00",“raw_price”:1492,“price”:“14,92\u00a0\u20ac”,“price_currency”:“EUR”,“price_faction_digits”:2,“price_base_unit”:100},“images”:{“small”:[{“url”:“http:\/\/example.com\/media\/product\/small\/288193_14.jpg”,“label”:“”}],“medium”:[{“url”:“http:\/\/example.com\/media\/product\/medium\/288193_14.jpg”,“label”:“”}],“large”:[{“url”:“http:\/\/example.com\/media\/product\/large\/288193_14.jpg”,“label”:“”}]}}],
        totalNumberOfResults = 1,
        productsPerPage = [{“number”:9,“selected”:true},{“number”:12,“selected”:false},{“number”:18,“selected”:false}],
        sortOrderConfig = ,
        translations = [],
        baseUrl = ‘http://example.com/‘,
        basePricePattern = ‘per %s%s %s &euro;‘;
</script>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**
Closes #1085.

### CODE REVIEW

File: src/ProductListing/Import/ProductListing.php [hunk 1]
```diff
@@ -47,45 +47,36 @@ public function __construct(
...
-        return serialize($this); // TODO: Use json_encode for serialization
+        return unserialize($serialized); // TODO: Use json_decode for unserialization
     }
 
-    public static function rehydrate($serialized) : ProductListing
+    public function getAttributesList(): ProductListingAttributeList
     {
-        return unserialize($serialized); // TODO: Use json_decode for unserialization
+        return $this->attributeList;
     }
```
Comment (tim-bezhashvyly) [inline src/ProductListing/Import/ProductListing.php]: This diff is confusing. What I in fact did here is added `getAttributesList` method and removed `hasAttribute` and `getAttributeValueByCode`.

File: src/ProductListing/Import/ProductListingMetaSnippetRenderer.php [hunk 2]
```diff
@@ -77,14 +77,14 @@ private function getProductListingMetaDataSnippetKey(ProductListing $productList
...
+    private function getPageMetaInfoSnippetContent(ProductListing $productListing): ProductListingMetaSnippetContent
     {
-        return ProductListingSnippetContent::create(
+        return ProductListingMetaSnippetContent::create(
             $productListing->getCriteria(),
             ProductListingTemplateSnippetRenderer::CODE,
             $this->getPageSnippetCodes($productListing),
             $containers = [],
-            $pageSpecificData = []
+            $pageSpecificData = ['product_listing_attributes' => $productListing->getAttributesList()->toArray()]
```
Comment (tim-bezhashvyly) [inline src/ProductListing/Import/ProductListingMetaSnippetRenderer.php]: Wanted to make it a constant but was not able to decide which class it belongs to.
