### PR TITLE
Issue #1067: Handle unknown HTTP request methods

### LINKED ISSUE #1067: Cleanly handle unsupported HTTP request methods
Currently unsupported HTTP request methods throw an uncaught exception.

```php
throw new UnsupportedRequestMethodException(
    sprintf('Unsupported request method: "%s"', $requestMethod)
);
```

If a robot crawls the site sending for example `PROPFIND` requests this ends up spamming the error log with noise.

Instead, a `405 Method Not Allowed` HTTP response should be sent.

### PR DESCRIPTION
**Pull request by Vinai**
Closes #1067

### CODE REVIEW

File: src/Http/HttpConnectRequest.php [hunk 1]
```diff
@@ -1,13 +0,0 @@
...
-
-namespace LizardsAndPumpkins\Http;
-
-class HttpConnectRequest extends HttpRequest
-{
-    public function getMethod(): string
-    {
-        return self::METHOD_CONNECT;
-    }
-}
```
Comment (tim-bezhashvyly) [inline src/Http/HttpConnectRequest.php]: 👍

File: src/Http/HttpOptionsRequest.php [hunk 2]
```diff
@@ -1,13 +0,0 @@
...
-
-namespace LizardsAndPumpkins\Http;
-
-class HttpOptionsRequest extends HttpRequest
-{
-    public function getMethod(): string
-    {
-        return self::METHOD_OPTIONS;
-    }
-}
```
Comment (tim-bezhashvyly) [inline src/Http/HttpOptionsRequest.php]: 👍

File: src/Http/HttpRequest.php [hunk 3]
```diff
@@ -15,9 +14,6 @@
     const METHOD_PUT = 'PUT';
     const METHOD_DELETE = 'DELETE';
     const METHOD_HEAD = 'HEAD';
-    const METHOD_OPTIONS = 'OPTIONS';
-    const METHOD_TRACE = 'TRACE';
-    const METHOD_CONNECT = 'CONNECT';
```
Comment (tim-bezhashvyly) [inline src/Http/HttpRequest.php]: 👍

File: src/Http/HttpUnknownMethodRequest.php [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+class HttpUnknownMethodRequest extends HttpRequest
+{
+    private $methodCode = '';
+    
+    public function getMethod(): string
+    {
+        return $this->methodCode;
+    }
+
+    public function setMethodCode(string $requestMethodCode)
```
Comment (tim-bezhashvyly) [inline src/Http/HttpUnknownMethodRequest.php]: Maybe a static constructor instead of a setter?
